# Generated by Django 3.2.13 on 2022-11-16 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='released_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='vote_average',
            new_name='vote_avg',
        ),
    ]
