# Generated by Django 3.2.13 on 2022-11-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='interested_genre',
            new_name='interested_genre1',
        ),
        migrations.AddField(
            model_name='user',
            name='interested_genre2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_genre3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
