# Generated by Django 3.2.13 on 2022-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_genre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
